schema: ./lib/graphql/schema.graphql
documents: ''
extensions:
  codegen:
    generates:
      ./lib/graphql/backend:
        plugins: []
      ./lib/graphql/frontend:
        plugins: []
  diff:
    baseSchema: your-base-schema-here
