// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6cqAxwwG5TsnK_XlPzUHu4dxP1ExBiUE',
    appId: '1:203738467816:web:3529bf803652bb5ad3e85d',
    messagingSenderId: '203738467816',
    projectId: 'soccer-app-a9060',
    authDomain: 'soccer-app-a9060.firebaseapp.com',
    storageBucket: 'soccer-app-a9060.appspot.com',
    measurementId: 'G-7CJJ1S2QCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvHFkoQb6Zo9z0_asEod7bzCekNXWrNhA',
    appId: '1:203738467816:android:f05c7c4f30736eecd3e85d',
    messagingSenderId: '203738467816',
    projectId: 'soccer-app-a9060',
    storageBucket: 'soccer-app-a9060.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVwwhIMyju-8G_lJ_8G6i_KzE0Pn2wf2E',
    appId: '1:203738467816:ios:d2a2ffff23af3005d3e85d',
    messagingSenderId: '203738467816',
    projectId: 'soccer-app-a9060',
    storageBucket: 'soccer-app-a9060.appspot.com',
    iosClientId: '203738467816-ft0u65aup2gk46kue5q6jkunfjihaei9.apps.googleusercontent.com',
    iosBundleId: 'com.example.soccermadeeasy',
  );
}
