import 'package:soccermadeeasy/graphql/fragments/team_fragments.dart';

class EventFragments {
  String eventGameFragment() {
    String eventGame = """
        _id
        archived
        deleted
        name
        isMainEvent
        type
        startTime
        endTime
        createdAt
        userParticipants{     
        data{
          _id
          event{                        
            _id
            name
          }
          user{
            _id
            name
            userType
          }
          roles
        }                                                              
      }
        location{
          data{
          _id
          latitude
          longitude
          }
        }
        games{
          data{
            _id
            pickup
          }
        }
        trainings{
          data{
            _id
          }
        }
        teams{
          data{
            ${TeamFragments().fullTeam()}
          }
        }
        price{
          _id
          amount
          event{
            _id
            name

          }
        }
        payments{
        data{
          _id
          amount
          user{
            _id
            name
          }
          event{
            _id
            name
          }
        }
      }
     """;
    return eventGame;
  }

  String fullEvent() {
    String fullEventReturn = """
      name        	
      _id  
      type                  
      archived
      isMainEvent
      deleted  
      startTime
      endTime  
      createdAt
      joinConditions{
        _id
        withRequest
        withPayment
      }
      price{                    
        _id
        amount
        event{
          _id
          name                      
        }
      }
      games{
          data{
            _id
            pickup
          }
        }
        trainings{
          data{
            _id
          }
        }
      teams{
          data{
            ${TeamFragments().fullTeam()}
          }
        }
      location{
        data{
        _id
        latitude
        longitude
        }
      }
      userParticipants{     
        data{
          _id
          event{                        
            _id
            name
          }
          user{
            _id
            name
            userType
          }
          roles
        }                                                              
      }
      payments{
        data{
          _id
          amount
          user{
            _id
            name
          }
          event{
            _id
            name
          }
        }
      }
    """;

    return fullEventReturn;
  }
}
